# ============================================================
#  SIMULATOR 切り替え (MODE=icarus / verilator)
# ============================================================
MODE  = icarus
#MODE  = verilator
SIM  := $(MODE)

sim_mmio_all:
	make -f Makefile.mmio.lcd simulate_PSC_LCD
	make -f Makefile.mmio.mic simulate_PSC_MIC 
	make -f Makefile.mmio.sd simulate_PSC_SD
	