// NISHIHARU
// lcd_test1.cpp  (PSC_LCD RGB666 / 32x32 image版)

#include <cstdint>

#define PIO32 (*reinterpret_cast<volatile uint32_t*>(0x10001000u))
static constexpr uint32_t TEST_END_CODE = 0xEE01;

#ifndef LCD_PIXS_ADDR_FPGA
#define LCD_PIXS_ADDR_FPGA  (0x10003000u)
#endif

#ifndef LCD_PIXS_DATA_FPGA
#define LCD_PIXS_DATA_FPGA  (0x10003004u)
#endif

#ifndef LCD_PIXS_ST_FPGA
#define LCD_PIXS_ST_FPGA    (0x10003008u)
#endif


constexpr uintptr_t LCD_PIXS_ADDR_BYTE  = LCD_PIXS_ADDR_FPGA;
constexpr uintptr_t LCD_PIXS_DATA_BYTE  = LCD_PIXS_DATA_FPGA;
constexpr uintptr_t LCD_PIXS_ST_BYTE    = LCD_PIXS_ST_FPGA;

#define MMIO32(addr_byte) (*reinterpret_cast<volatile uint32_t*>(addr_byte))

static constexpr uint32_t LCD_W = 320;
static constexpr uint32_t LCD_H = 480;

extern "C" volatile uint32_t result;
extern "C" volatile uint32_t result_wr;
extern "C" volatile uint32_t result_rd;
extern "C" volatile uint32_t result_ok;

// RGB666: [17:12]=R, [11:6]=G, [5:0]=B
static constexpr uint32_t RGB666(uint32_t r, uint32_t g, uint32_t b)
{
    return ((r & 0x3F) << 12) |
           ((g & 0x3F) <<  6) |
           ((b & 0x3F) <<  0);
}

static constexpr uint32_t C_BLACK = RGB666(0,  0,  0);
static constexpr uint32_t C_RED   = RGB666(63, 0,  0);
static constexpr uint32_t C_GREEN = RGB666(0,  63, 0);
static constexpr uint32_t C_BLUE  = RGB666(0,  0,  63);
static constexpr uint32_t C_WHITE = RGB666(63, 63, 63);
static constexpr uint32_t C_YEL   = RGB666(63, 63, 0);

// 32x32 テスト画像
static const uint32_t image32x32[32][32] =
{
    { C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED },
    { C_RED,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_RED },
    { C_RED,C_YEL,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_YEL,C_RED },
    { C_RED,C_YEL,C_GREEN,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_GREEN,C_YEL,C_RED },

    { C_RED,C_YEL,C_GREEN,C_BLUE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_BLUE,C_GREEN,C_YEL,C_RED },
    { C_RED,C_YEL,C_GREEN,C_BLUE,C_WHITE,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_WHITE,C_BLUE,C_GREEN,C_YEL,C_RED },
    { C_RED,C_YEL,C_GREEN,C_BLUE,C_WHITE,C_BLACK,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_BLACK,C_WHITE,C_BLUE,C_GREEN,C_YEL,C_RED },
    { C_RED,C_YEL,C_GREEN,C_BLUE,C_WHITE,C_BLACK,C_RED,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_RED,C_BLACK,C_WHITE,C_BLUE,C_GREEN,C_YEL,C_RED },

    { C_RED,C_YEL,C_GREEN,C_BLUE,C_WHITE,C_BLACK,C_RED,C_GREEN,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_GREEN,C_RED,C_BLACK,C_WHITE,C_BLUE,C_GREEN,C_YEL,C_RED },
    { C_RED,C_YEL,C_GREEN,C_BLUE,C_WHITE,C_BLACK,C_RED,C_GREEN,C_BLUE,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_BLUE,C_GREEN,C_RED,C_BLACK,C_WHITE,C_BLUE,C_GREEN,C_YEL,C_RED },
    { C_RED,C_YEL,C_GREEN,C_BLUE,C_WHITE,C_BLACK,C_RED,C_GREEN,C_BLUE,C_YEL,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_YEL,C_BLUE,C_GREEN,C_RED,C_BLACK,C_WHITE,C_BLUE,C_GREEN,C_YEL,C_RED },
    { C_RED,C_YEL,C_GREEN,C_BLUE,C_WHITE,C_BLACK,C_RED,C_GREEN,C_BLUE,C_YEL,C_WHITE,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_WHITE,C_YEL,C_BLUE,C_GREEN,C_RED,C_BLACK,C_WHITE,C_BLUE,C_GREEN,C_YEL,C_RED },

    { C_RED,C_YEL,C_GREEN,C_BLUE,C_WHITE,C_BLACK,C_RED,C_GREEN,C_BLUE,C_YEL,C_WHITE,C_BLACK,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_BLACK,C_WHITE,C_YEL,C_BLUE,C_GREEN,C_RED,C_BLACK,C_WHITE,C_BLUE,C_GREEN,C_YEL,C_RED },
    { C_RED,C_YEL,C_GREEN,C_BLUE,C_WHITE,C_BLACK,C_RED,C_GREEN,C_BLUE,C_YEL,C_WHITE,C_BLACK,C_RED,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_RED,C_BLACK,C_WHITE,C_YEL,C_BLUE,C_GREEN,C_RED,C_BLACK,C_WHITE,C_BLUE,C_GREEN,C_YEL,C_RED },
    { C_RED,C_YEL,C_GREEN,C_BLUE,C_WHITE,C_BLACK,C_RED,C_GREEN,C_BLUE,C_YEL,C_WHITE,C_BLACK,C_RED,C_GREEN,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_GREEN,C_RED,C_BLACK,C_WHITE,C_YEL,C_BLUE,C_GREEN,C_RED,C_BLACK,C_WHITE,C_BLUE,C_GREEN,C_YEL,C_RED },
    { C_RED,C_YEL,C_GREEN,C_BLUE,C_WHITE,C_BLACK,C_RED,C_GREEN,C_BLUE,C_YEL,C_WHITE,C_BLACK,C_RED,C_GREEN,C_BLUE,C_WHITE,C_WHITE,C_BLUE,C_GREEN,C_RED,C_BLACK,C_WHITE,C_YEL,C_BLUE,C_GREEN,C_RED,C_BLACK,C_WHITE,C_BLUE,C_GREEN,C_YEL,C_RED },

    { C_RED,C_YEL,C_GREEN,C_BLUE,C_WHITE,C_BLACK,C_RED,C_GREEN,C_BLUE,C_YEL,C_WHITE,C_BLACK,C_RED,C_GREEN,C_BLUE,C_WHITE,C_WHITE,C_BLUE,C_GREEN,C_RED,C_BLACK,C_WHITE,C_YEL,C_BLUE,C_GREEN,C_RED,C_BLACK,C_WHITE,C_BLUE,C_GREEN,C_YEL,C_RED },
    { C_RED,C_YEL,C_GREEN,C_BLUE,C_WHITE,C_BLACK,C_RED,C_GREEN,C_BLUE,C_YEL,C_WHITE,C_BLACK,C_RED,C_GREEN,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_GREEN,C_RED,C_BLACK,C_WHITE,C_YEL,C_BLUE,C_GREEN,C_RED,C_BLACK,C_WHITE,C_BLUE,C_GREEN,C_YEL,C_RED },
    { C_RED,C_YEL,C_GREEN,C_BLUE,C_WHITE,C_BLACK,C_RED,C_GREEN,C_BLUE,C_YEL,C_WHITE,C_BLACK,C_RED,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_RED,C_BLACK,C_WHITE,C_YEL,C_BLUE,C_GREEN,C_RED,C_BLACK,C_WHITE,C_BLUE,C_GREEN,C_YEL,C_RED },
    { C_RED,C_YEL,C_GREEN,C_BLUE,C_WHITE,C_BLACK,C_RED,C_GREEN,C_BLUE,C_YEL,C_WHITE,C_BLACK,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_BLACK,C_WHITE,C_YEL,C_BLUE,C_GREEN,C_RED,C_BLACK,C_WHITE,C_BLUE,C_GREEN,C_YEL,C_RED },

    { C_RED,C_YEL,C_GREEN,C_BLUE,C_WHITE,C_BLACK,C_RED,C_GREEN,C_BLUE,C_YEL,C_WHITE,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_WHITE,C_YEL,C_BLUE,C_GREEN,C_RED,C_BLACK,C_WHITE,C_BLUE,C_GREEN,C_YEL,C_RED },
    { C_RED,C_YEL,C_GREEN,C_BLUE,C_WHITE,C_BLACK,C_RED,C_GREEN,C_BLUE,C_YEL,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_YEL,C_BLUE,C_GREEN,C_RED,C_BLACK,C_WHITE,C_BLUE,C_GREEN,C_YEL,C_RED },
    { C_RED,C_YEL,C_GREEN,C_BLUE,C_WHITE,C_BLACK,C_RED,C_GREEN,C_BLUE,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_BLUE,C_GREEN,C_RED,C_BLACK,C_WHITE,C_BLUE,C_GREEN,C_YEL,C_RED },
    { C_RED,C_YEL,C_GREEN,C_BLUE,C_WHITE,C_BLACK,C_RED,C_GREEN,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_GREEN,C_RED,C_BLACK,C_WHITE,C_BLUE,C_GREEN,C_YEL,C_RED },

    { C_RED,C_YEL,C_GREEN,C_BLUE,C_WHITE,C_BLACK,C_RED,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_RED,C_BLACK,C_WHITE,C_BLUE,C_GREEN,C_YEL,C_RED },
    { C_RED,C_YEL,C_GREEN,C_BLUE,C_WHITE,C_BLACK,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_BLACK,C_WHITE,C_BLUE,C_GREEN,C_YEL,C_RED },
    { C_RED,C_YEL,C_GREEN,C_BLUE,C_WHITE,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_BLACK,C_WHITE,C_BLUE,C_GREEN,C_YEL,C_RED },
    { C_RED,C_YEL,C_GREEN,C_BLUE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_WHITE,C_BLUE,C_GREEN,C_YEL,C_RED },

    { C_RED,C_YEL,C_GREEN,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_BLUE,C_GREEN,C_YEL,C_RED },
    { C_RED,C_YEL,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_GREEN,C_YEL,C_RED },
    { C_RED,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_YEL,C_RED },
    { C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED,C_RED }
};

static inline void tiny_delay(unsigned n)
{
    while (n--) {
        asm volatile("nop");
    }
}

void lcd_write_pix32x32(
    uint32_t start_px,
    uint32_t start_py,
    const uint32_t img[32][32]
)
{
    if (start_px >= LCD_W || start_py >= LCD_H) {
        return;
    }

    result_rd = (start_py << 9) | start_px;

    MMIO32(LCD_PIXS_ADDR_BYTE) = result_rd;

    for (uint32_t y = 0; y < 32; y++) {
        for (uint32_t x = 0; x < 32; x++) {
            //uint32_t pix = img[y][x] & 0x3FFFFu;
            uint32_t pix = y<<5 | (x + 0x01);

            result_wr = pix;
            MMIO32(LCD_PIXS_DATA_BYTE) = pix;
        }
    }

    // write_ready = H wait.
    uint32_t timeout = 200000;  // 適宜調整
    while ((MMIO32(LCD_PIXS_ST_BYTE) & 0x01u) == 0x01u) {
        if (--timeout == 0) {
            PIO32 = 0xEE03;
            break;
        }
        __asm__ __volatile__("nop");
    }

    // debug log.
    result = MMIO32(LCD_PIXS_ST_BYTE);
    PIO32   = result;

    result_ok = 1;
}

extern "C" void run()
{
    result = 0x07u;
    PIO32 = result;

    while (1) {
        lcd_write_pix32x32(14, 20, image32x32);

        //lcd_write_pix32x32(24, 40, image32x32);

        tiny_delay(1000);

        PIO32 = TEST_END_CODE;
        PIO32 = 0x0012;

        tiny_delay(100);
    }

    while (1) {
    }
}

extern "C" {
    volatile uint32_t result    = 0;
    volatile uint32_t result_wr = 0;
    volatile uint32_t result_rd = 0;
    volatile uint32_t result_ok = 0;
}